df_Y = pd.read_csv('./asset/wire_saw_summary/sfqr/all_minmax_with_predictions_and_importance.csv', low_memory=False)


1. df_Y 데이터에 EQP_ID_MODULE_NAME열에 eqp_1로 그룹화
2. d 열만 추출하고 각 열 평균하기.
 d = ['SLOT_NO_importance','RECIPE_ID_importance',
 'AVG_ROTATION_SPEED_AT_CH_MOTIONCTRL_ROTATION_RVEL_STEP_MEAN_importance',
 'BLOWER_AIR_BOTTOM_PRESSURE_BOTTOM_AT_CHA_STEP_MEAN_importance',
 'BLOWER_AIR_PRESSURE_AT_CHA_STEP_MEAN_importance',
 'CURRENT_FLOW_AT_CH_GASPANEL_STICK01_MFC_RFLOW_STEP_MEAN_importance',
 'CURRENT_FLOW_AT_CH_GASPANEL_STICK02_MFC_RFLOW_STEP_MEAN_importance',
 'CURRENT_FLOW_AT_CH_GASPANEL_STICK03_MFC_RFLOW_STEP_MEAN_importance',
 'CURRENT_FLOW_AT_CH_GASPANEL_STICK04_MFC_RFLOW_STEP_MEAN_importance',
 'CURRENT_FLOW_AT_CH_GASPANEL_STICK05_MFC_RFLOW_STEP_MEAN_importance',
 'CURRENT_FLOW_AT_CH_GASPANEL_STICK06_MFC_RFLOW_STEP_MEAN_importance',
 'LIFT_TORQUE_AT_CHA_MOTIONCTRL_LIFT_RTORQUE_STEP_MEAN_importance',
 'PRESSURE_AT_BUFFER_VACSYS_PRESSGAUGE_RPRESSURE_STEP_MEAN_importance',
 'PRESSURE_AT_CH_MAN1000T_RPRESSURE_STEP_MEAN_importance',
 'SCR_POWER_AT_CH_TEMPCTRL_HEATER_TOP_INNER_RPOWER_STEP_MEAN_importance',
 'SCR_POWER_AT_CH_TEMPCTRL_HEATER_TOP_OUTER_RPOWER_STEP_MEAN_importance',
 'SCR_POWER_AT_CH_TEMPCTRL_HEATER_BOTTOM_INNER_RPOWER_STEP_MEAN_importance',
 'SCR_POWER_AT_CH_TEMPCTRL_HEATER_BOTTOM_OUTER_RPOWER_STEP_MEAN_importance',
 'TEMPERATURE_READING_AT_CH_TEMPCTRL_HEATER_BOTTOM_PYROMETER_RTEMP_STEP_MEAN_importance',
 'TEMPERATURE_READING_AT_CH_TEMPCTRL_HEATER_EDGE_PYROMETER_RTEMP_STEP_MEAN_importance',
 'TEMPERATURE_READING_AT_CH_TEMPCTRL_HEATER_TOP_PYROMETER_RTEMP_STEP_MEAN_importance',
 'VP_ACCUSET_IN_STEP_MEAN_importance',
 'VP_ACCUSET_OUT_STEP_MEAN_importance',
 'VP_MULTIRUN_ORDER_STEP_MEAN_importance',
 'VP_RCP_CNT_STEP_MAX_importance',
 'VP_SUSCEPTORHEIGHT_STEP_MAX_importance',
 'VP_RCP_CNT2_STEP_MAX_importance',
 'CH_SAVED_TRAINED_EXTENDED_EXTENSION_B1_STEP_MEAN_importance',
 'CH_SAVED_TRAINED_EXTENDED_ROTATION_B1_STEP_MEAN_importance',
 'ACTUAL_SPEED_AT_CH_TEMPCTRL_HEATER_BOTTOM_VSB_RSPEED_STEP_MEAN_importance',
 'ACTUAL_SPEED_AT_CH_TEMPCTRL_HEATER_TOP_VSB_RSPEED_STEP_MEAN_importance',
 'ZDDFRONTMEAN_01_AFS2_SUB_importance']

3. 평균한 열 값 큰 수로 정렬하고 아래에 맞게 수정

chart = alt.Chart(df_fdc.iloc[:10]).mark_bar(color = '#E1002A').encode(
    x = alt.X('SCORE', title = 'IMPORTANCE (%)'),
    y = alt.Y('col', title = None, sort = '-x', axis = alt.Axis(labelLimit = 200))
)

st.altair_chart(chart, use_container_width = True)
