import pandas as pd

# CSV 파일 로드
df = pd.read_csv("x.csv")

# 사용자가 제공한 열 목록
columns_to_extract = [
    "STEP_TIME_RMS_PROC", "PROCESS-BAKE2-MAIN_H2", "PROCESS-DEPO-WITHOUT_TEMP", "PROCESS-POST_PURGE-TEMP",
    "PROCESS-COOL3-LIFT_POS", "PROCESS-DEPO-SUS_HEIGHT2", "PROCESS-PURGE-ACC_IN", "PROCESS-RAMP_UP-TEMP",
    "PROCESS-POST_PURGE-ACC_IN", "PROCESS-COOL3-ACC_OUT", "PROCESS-DEPO-SLIT_H2", "PROCESS-BAKE2-ACC_IN",
    "PROCESS-BAKE1-ACC_OUT", "PROCESS-COOL3-MAIN_H2", "PROCESS-BAKE2-ACC_OUT", "PROCESS-BAKE2-SUS_HEIGHT2",
    "PROCESS-COOL3-ACC_IN", "PROCESS-POST_PURGE-SUS_HEIGHT2", "PROCESS-DEPO-LOAD_DELAY", "PROCESS-PRE_VENT-ACC_OUT",
    "PROCESS-PRE_VENT-TCS", "PROCESS-PURGE-SUS_HEIGHT2", "PROCESS-BAKE1-TEMP", "PROCESS-COOL3-SUS_HEIGHT2",
    "PROCESS-BAKE1-SUS_HEIGHT2", "PROCESS-COOL2-SLIT_H2", "PROCESS-COOL1-ACC_IN", "PROCESS-DEPO-MAIN_H2",
    "PROCESS-PRE_VENT-SUS_HEIGHT2", "PROCESS-COOL2-SUS_HEIGHT2", "PROCESS-BAKE1-ACC_IN", "PROCESS-DEPO-MULTIRUN_SET",
    "PROCESS-PRE_VENT-SLIT_H2", "PROCESS-RAMP_UP-MAIN_H2", "PROCESS-COOL1-SLIT_H2", "PROCESS-POST_PURGE-VSBSPEED",
    "PROCESS-PURGE-SLIT_H2", "PROCESS-COOL1-ACC_OUT", "PROCESS-COOL2-MAIN_H2", "PROCESS-POST_PURGE-MAIN_H2",
    "PROCESS-COOL1-MAIN_H2", "PROCESS-PRE_VENT-VSBSPEED", "PROCESS-COOL2-ACC_IN", "PROCESS-COOL3-SLIT_H2",
    "PROCESS-RAMP_UP-SLIT_H2", "PROCESS-PRE_VENT-ACC_IN", "PROCESS-DEPO-WITH_TEMP", "PROCESS-DEPO-ACC_OUT",
    "PROCESS-DEPO-VSBSPEED", "PROCESS-COOL2-VSBSPEED", "PROCESS-PURGE-VSBSPEED", "PROCESS-DEPO-XFER_POWER",
    "PROCESS-RAMP_UP-SUS_HEIGHT2", "PROCESS-COOL3-VSBSPEED", "PROCESS-RAMP_UP-ACC_OUT", "PROCESS-POST_PURGE-SLIT_H2",
    "PROCESS-DEPO-ACTIVE_POWER", "PROCESS-BAKE1-MAIN_H2", "PROCESS-COOL2-ACC_OUT", "PROCESS-BAKE2-TEMP",
    "PROCESS-PRE_VENT-MAIN_H2", "PROCESS-BAKE1-VSBSPEED", "PROCESS-PRE_VENT-TEMP", "PROCESS-RAMP_UP-VSBSPEED",
    "PROCESS-DEPO-TCS", "PROCESS-BAKE1-SLIT_H2", "PROCESS-DEPO-TEMP", "PROCESS-POST_PURGE-ACC_OUT",
    "PROCESS-BAKE2-VSBSPEED", "PROCESS-COOL1-SUS_HEIGHT2", "PROCESS-PURGE-MAIN_H2", "PROCESS-BAKE2-SLIT_H2",
    "PROCESS-RAMP_UP-ACC_IN", "PROCESS-PURGE-ACC_OUT", "PROCESS-DEPO-ACC_IN", "PROCESS-COOL1-VSBSPEED",
    "PROCESS-DEPO-LIFT_CAL", "RMS_CLEAN", "CLEAN-PURGE-ACC_IN", "CLEAN-RAMP_DOWN-SUS_HEIGHT2",
    "CLEAN-RAMP_DOWN-SLIT_H2", "CLEAN-BAKE-SUS_HEIGHT2", "CLEAN-PRE_VENT-SLIT_H2", "CLEAN-COOL-SUS_HEIGHT2",
    "CLEAN-BAKE-MAIN_H2", "CLEAN-COAT-TCS", "CLEAN-PRE_VENT-TEMP", "CLEAN-COAT-SUS_HEIGHT2", "CLEAN-COOL-VSBSPEED",
    "CLEAN-ETCH-ACC_IN", "CLEAN-RAMP_DOWN-MAIN_H2", "CLEAN-PURGE-SLIT_H2", "CLEAN-RAMP_UP-MAIN_H2",
    "CLEAN-PRE_VENT-MAIN_H2", "CLEAN-COOL-MAIN_H2", "CLEAN-BAKE-ACC_OUT", "CLEAN-COAT-SLIT_H2",
    "CLEAN-ETCH-MAIN_H2", "CLEAN-RAMP_UP-TEMP", "CLEAN-PRE_VENT-VSBSPEED", "CLEAN-COAT-VSBSPEED",
    "CLEAN-PRE_VENT-SUS_HEIGHT2", "CLEAN-RAMP_UP-VSBSPEED", "CLEAN-RAMP_DOWN-TCS", "CLEAN-ETCH-ACC_OUT",
    "CLEAN-BAKE-TEMP", "CLEAN-COOL-SLIT_H2", "CLEAN-ETCH-VSBSPEED", "CLEAN-RAMP_UP-SUS_HEIGHT2",
    "CLEAN-COAT-MAIN_H2", "CLEAN-PURGE-MAIN_H2", "CLEAN-ETCH-TEMP", "CLEAN-PRE_VENT-ACC_IN", "CLEAN-PURGE-SUS_HEIGHT2",
    "CLEAN-COAT-ACC_IN", "CLEAN-ETCH-SUS_HEIGHT2", "CLEAN-POST_PURGE-SLIT_H2", "CLEAN-POST_PURGE-MAIN_H2",
    "CLEAN-ETCH-SLIT_H2", "CLEAN-RAMP_DOWN-VSBSPEED", "CLEAN-RAMP_UP-ACC_IN", "CLEAN-RAMP_UP-SLIT_H2",
    "CLEAN-PRE_VENT-ACC_OUT", "CLEAN-POST_PURGE-VSBSPEED", "CLEAN-COOL-ACC_IN", "CLEAN-RAMP_DOWN-ACC_IN",
    "CLEAN-POST_PURGE-SUS_HEIGHT2", "CLEAN-POST_PURGE-ACC_IN", "CLEAN-PURGE-VSBSPEED", "PROCESS-DEPO-AUX",
    "PROCESS-DEPO-DOPANT", "PROCESS-DEPO-POW_BOT", "PROCESS-DEPO-POW_BOT_IN", "PROCESS-DEPO-POW_TOP_IN",
    "PROCESS-DEPO-RPM_ACT", "PROCESS-DEPO-TOP_EMISS", "PROCESS-DEPO-BOTTOM_EMISS", "SUS_SUP_WAFER-ARM_LEN_B",
    "SUS_SUP_WAFER-ARM_LEN_L", "SUS_SUP_WAFER-ARM_LEN_R", "SUS_SUP_WAFER-ARM_ANGL_B", "SUS_SUP_WAFER-ARM_ANGL_L",
    "SUS_SUP_WAFER-ARM_ANGL_R", "SUS_SUP_WAFER-FLAT_A", "SUS_SUP_WAFER-FLAT_B", "SUS_SUP_WAFER-FLAT_L",
    "SUS_SUP_WAFER-FLAT_R", "WAVY_HOLED_SUSCEP-SUSCEPTOR_D_3D", "WAVY_HOLED_SUSCEP-CENTER_TO_P0_3D",
    "WAVY_HOLED_SUSCEP-CENTER_TO_P110_3D", "WAVY_HOLED_SUSCEP-CENTER_TO_P100_3D", "WAVY_HOLED_SUSCEP-POCKET_HEIGHT_3D",
    "WAVY_HOLED_SUSCEP-LEDGE_HEIGHT_3D", "WAVY_HOLED_SUSCEP-LEDGE_DISTANCE110_3D", "WAVY_HOLED_SUSCEP-LEDGE_DISTANCE100_3D",
    "WAVY_HOLED_SUSCEP-LEDGE_FLATNESS_3D", "WAVY_HOLED_SUSCEP-LEDGE_ANGLE_3D", "WAVY_HOLED_SUSCEP-INNER_DEPTH_AVG_3D"
]

# 존재하는 열만 선택하여 새로운 데이터프레임 생성
df_extracted = df[[col for col in columns_to_extract if col in df.columns]]

# 변환된 CSV 저장
df_extracted.to_csv("x_extracted.csv", index=False)
print("추출 완료: x_extracted.csv 저장됨")